version: '3'

services:
  app:
    container_name: app-$POSTFIX
    build:
      context: ./
    ports:
      - "${WEB_PORT_LOCAL}:${WEB_PORT}"
    image: mafio69/php81
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVERNAME=${SERVERNAME}
      - SERVERALIAS=${SERVERALIAS}
      - DRUSH_VERSION=8/9
      - WEB_PORT=${WEB_PORT:-8070}
      - APP_NAME=${APP_NAME:-webwizards}
      - DB_HOST=${DB_HOST:-database}
      - APP_ENV=${APP_ENV:-local}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - APP_DEBUG=${APP_DEBUG:-1}
      - EMAIL_USER=${EMAIL_USER:-user}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-password}
      - EMAIL_HOST=${EMAIL_HOST:-mailtrap}
      - DISPLAY_ERROR=${DISPLAY_ERROR:-on}
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9003}
    volumes:
      - ./main:/main
    links:
      - database:mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT_LOCAL}" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mailtrap:
    container_name: mailtrap-$POSTFIX
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1039:1025" # smtp server
      - "8039:8025" # web ui

  redis:
    image: bitnami/redis:6.2.6-debian-10-r117
    container_name: redis-$POSTFIX
    restart: always
    ports:
      - "7004:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  database:
    container_name: mysql-$POSTFIX
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT}"
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

